### ISSUE TITLE
Segmentation fault when trying to install through pip3

### ISSUE THREAD

**Issue by MaineC** [LABHR/octohatrack#100]
Environment:
- Ubuntu 17.10
- pip3

Executed command:
`pip3 install octohatrack`

Expected output: Installed package.

Actual output:

    Collecting octohatrack
    Collecting gitpython (from octohatrack)
      Using cached GitPython-2.1.8-py2.py3-none-any.whl
    Collecting requests (from octohatrack)
      Using cached requests-2.18.4-py2.py3-none-any.whl
    Collecting simplejson (from octohatrack)
    Collecting gitdb2>=2.0.0 (from gitpython->octohatrack)
      Using cached gitdb2-2.0.3-py2.py3-none-any.whl
    Collecting idna<2.7,>=2.5 (from requests->octohatrack)
      Using cached idna-2.6-py2.py3-none-any.whl
    Collecting urllib3<1.23,>=1.21.1 (from requests->octohatrack)
      Using cached urllib3-1.22-py2.py3-none-any.whl
    Collecting chardet<3.1.0,>=3.0.2 (from requests->octohatrack)
      Using cached chardet-3.0.4-py2.py3-none-any.whl
    Collecting certifi>=2017.4.17 (from requests->octohatrack)
      Using cached certifi-2017.11.5-py2.py3-none-any.whl
    Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->gitpython->octohatrack)
      Using cached smmap2-2.0.3-py2.py3-none-any.whl
    Installing collected packages: smmap2, gitdb2, gitpython, idna, urllib3, chardet, certifi, requests,     simplejson, octohatrack
    Successfully installed certifi-2017.11.5 chardet-3.0.4 gitdb2-2.0.3 gitpython-2.1.8 idna-2.6     octohatrack-0.6.1 requests-2.18.4 simplejson-3.13.2 smmap2-2.0.3 urllib3-1.22
    Segmentation fault (core dumped)

**Comment by MaineC** [comment]
Note: Not a python expert here, so any help with debugging the segfault welcome as well.

**Comment by MaineC** [comment]
PEBCAK - adding sudo permissions helped

**Comment by glasnt** [comment]
Glad to hear you got it working 😊

**Comment by MaineC** [comment]
Hat Tip to my husband @t-lo for the remote debugging help :)
