### ISSUE TITLE
Show also commits, additions and deletions of a contributor in the list

### ISSUE THREAD

**Issue by skilldeliver** [LABHR/octohatrack#106]
For example, this would be very handy for showing top10 contributors of a repo.

**Comment by glasnt** [comment]
Hi @skilldeliver. This is outside of scope, as it's this exact ranking of the worth of a contributor by lines of code that is wrong with GitHub in the first place. 

You can see this data natively on GitHub by looking at the `/graphs/contributors` page for a repo.
