### ISSUE TITLE
Issues of optional arguments

### ISSUE THREAD

**Issue by Jiagod** [LABHR/octohatrack#112]
When I enter octohatrack -h, the result is as follows
optional arguments:
  -h, --help show this help message and exit
--no-cache Disable local caching of API results
-v, --version show program's version number and exit
  -l 10, --limit 10 Limit to the last x Issues/Pull Requests
Which version should I use or what should I do to get the optional arguments as shown in the readme?

**Comment by glasnt** [comment]
Hi @Jiagod 

This is a different question than what you asked by email. 

`-h` and `-v` in this case just show information about octohatrack itself and then the program exists. 

You can run `octohatrack username/repo` without any arguments and get results. For older/busier repos, you can limit the results with `-l` for faster, more recent results. You can also disable cache if you do not want that option. 

I'm not sure if this answers your question.

**Comment by Jiagod** [comment]
I want to chose "--wait-for-reset" this option, so I put -h to check information about octohatrack. But the result show in the screen is -h, -no-cache, -v, -l 10, Instead of -v, -no-cache, -wait-for-reset, -v mentioned in the readme. I don't know what caused this result.

**Comment by glasnt** [comment]
Which version of octohatrack do you have installed? 

Run: `octohatrack -v`

**Comment by glasnt** [comment]
I think I have found the problem, and you are right, @Jiagod 

I haven't released a version of octohatrack to pypi in years. If you are installing from there, the version you get will be severely out of date. 

My sincere apologise. I will get this fixed and let you know.

**Comment by Jiagod** [comment]
Thank you very much.

**Comment by glasnt** [comment]
Hi @Jiagod, you should be able to install v1.0.1 from PyPI now, which includes the `--wait-for-reset` functionality update

**Comment by Jiagod** [comment]
I ran pip3 install octohatrack again, but it doesn’t seem to be updated yet, the version of octohatrack is still 0.6.1

**Comment by glasnt** [comment]
Try installing it directly

pip install octohatrack==1.0.1

**Comment by Jiagod** [comment]
It work. Thank you again.
