### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by glasnt** [LABHR/octohatrack#113]
Probably would mock github responses, and/or do a self live test.

**Comment by glasnt** [comment]
live test doesn't work, because the automatically generated GITHUB_TOKEN doesn't have permissions to do the functionality required. 

I also wrote the README before(?) personal tokens had such a spread of access options, so I need to go back and confirm the permissions required, update the README, then work out how to test when I can't use the varname I have in the code

**Comment by Jiagod** [comment]
I have encountered this issuses. When I use octohatrack version 0.6.0 and python version 2.7, the result of the test is only "All contributors list" as it is now. The "Github contributors list" is missing. But when I use pyton3, the problem is solved.

**Comment by glasnt** [comment]
Python 2.7 [has been sunset](https://www.python.org/doc/sunset-python-2/); octohatrack predates this, but was always designed for Python 3 only, and did have code to [exit early if Python 2.7 was being used](https://github.com/LABHR/octohatrack#python-3-requirement) (though that code must not be working if you're able to get some results)

**Comment by glasnt** [comment]
> live test doesn't work, because the automatically generated GITHUB_TOKEN doesn't have permissions to do the functionality required.

Incorrect; this was an issue because I was mishandling the use case where no GITHUB_TOKEN was defined. Fixed in 2e843133

Integration tests now work.
