### ISSUE TITLE
pull data from Bugzilla

### ISSUE THREAD

**Issue by stewart-ibm** [LABHR/octohatrack#13]
This is totally a wishlist item.

we have an internal Bugzilla instance, it's even linked into *other* bug systems (big company)

There is an upcoming REST API to Bugzilla, but in the meantime there's the old XMLRPC one ( https://www.bugzilla.org/docs/4.4/en/html/api/Bugzilla/WebService/Server/XMLRPC.html ).

Through that, it should be possible to search for bugs on a particular product and extract who's filing and commenting on them.

**Comment by glasnt** [comment]
Hi Stewart! This is an awesome idea.

My main thoughts lie in whether octohat should stay just github-related, or if it should be expanded to allow for other types of source control systems. If that's the case, do you think it would be wise to say have a set flag to say "github" or "bugzilla" with a sufficiently defined identifier for these types?

e.g. github -> `(user)/(repo)` -> `https://api.github.com/repos/(input)`
bugzilla -> `??`

The less human input required the better, but I'm unsure what the requirements for uniquely identifying a bugzilla repo is.

What are your thoughts on this?

**Comment by stewart-ibm** [comment]
It may be good if it just has plugins for different systems, so people can choose as many / as few as they like, depending on needs.

For uniquely identifying a bugzilla repo, it's basically a URL to the bugzilla instance and then you'll want to specify query parameters (so that you only pull bugs that are related to your project - for example, our bugzilla instance contains bugs for pretty much everything the Linux Technology Center touches... which is a *LOT*).

**Comment by glasnt** [comment]
Cheers, I'll look into getting a prototype working for bugzilla data

**Comment by glasnt** [comment]
I'm going to close this issue against the github project and refer to the labhr/labhr.github.io#1 issue above for further information.
