### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0153' in position 1

### ISSUE THREAD

**Issue by jniggemann** [LABHR/octohatrack#42]
This error is reproducible with python 2.7.9 on Debian 8.1:
U+0153 is LATIN SMALL LIGATURE OE: œ

```
$> octohat -g sebsauvage/MinigalNano
Collecting contributors....
Collecting commentors...........................................................
................................................................................                                                                              
Code contributions: 11
Non-code contributions: 28
jdedba
AnatomicJC
Riduidel
andersk
Niols
cepcasa
qwertygc
bitbybit
ygbillet
thomas30
Denys06
meh-uk
cborne
lanner
fufroma
k1ka
jabalv
10cre
indoushka
arthurlutz
farbrorlarry
nicosomb
Mermouy
fpp-gh
patcou
fredtantini
Knah-Tsaeb
danc
Traceback (most recent call last):
  File "/usr/local/bin/octohat", line 9, in <module>
    load_entry_point('octohat==0.1.3', 'console_scripts', 'octohat')()
  File "/usr/local/lib/python2.7/dist-packages/octohat/__init__.py", line 59, in
 main
    f.write(display_user_html(user, args))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0153' in position 1
97: ordinal not in range(128)
```

**Comment by glasnt** [comment]
Hi! Thanks for reporting this @jniggemann 

Are you able to see if this is still an issue in python3? I'm not sure if it's trivial to fix unicode in python2.7, because I'm not a python developer, but I think it's literally just the writing to file that's not working properly.

**Comment by jniggemann** [comment]
Tried with python3, no errors. Nevertheless, the Name "Nicolas Lœuillet" (https://github.com/nicosomb) is output as "Nicolas LÅ“uillet" in the html output: `<div>Nicolas LÅ“uillet</div>`

**Comment by glasnt** [comment]
Hi @jniggemann, turns out I was just missing the `charset` tag on the generated HTML. Cheers to @dshafik for pointing out this solution. Your generated output should work now. Note that I'll need to bump the package version for this to work from pip; in the mean time you can use `python3 octohatrack.py` from a local clone of this repo.

**Comment by dshafik** [comment]
Glad this worked for you @glasnt! 🎉
