### ISSUE TITLE
Does octohatrack include wiki edits?

### ISSUE THREAD

**Issue by brainwane** [LABHR/octohatrack#67]
I did a quick look and it looks like the project doesn't currently include/count wiki edits as a form of contribution. Did I miss something? Is this planned? If not, I could help implement that.

**Comment by glasnt** [comment]
Hi! Yes, I agree that wiki edits should count. The original vendor library I was using didn't nicely handle that, so I had it on the TODO list (which is apparently out of date now). 

From what I recall the api is a bit different than with normal edits, but my plan was to see if the new shiny api library (as mentioned in #66) natively handles wiki edits. If not, that could be something to implement locally or upstream.

**Comment by glasnt** [comment]
This one is going to be fun to implement

There's no API for the wikis. There's only `Gollum` events in the event API, but that's only the last 300 events for the past 90 days. 

The only way to get all the contributors is to work the wiki in it's base git repo form, and get a list of contributors that way. You can only get out the git form, which may/may not be able to be mapped back to GitHub users. Guessing that display names of GitHub users may match git username configurations may help, but it's not a fool-proof method. 

I'm tempted to implement this as a addition set of contributors, for now at least. 

When this goes into js-hatrack (can you even do git manipulation in raw JS?) the gravatar-matching method may have to be used for getting a visual token.

**Comment by glasnt** [comment]
Implemented Experimentally in #73! :tada:
