### ISSUE TITLE
Unbreak local invocation mechanism

### ISSUE THREAD

**Issue by glasnt** [LABHR/octohatrack#72]
I think I need to find someone one to explain this one to me IRL because I'm not getting it. 

What I want: 
 * `pip install octohatrack; octohatrack blah/blah` to "just work" as a command-line tool
 * `git clone https://github.com/labhr/octohatrack; cd octohatrack; python3 somefile.py blah/blah` to "just work" as an invocation of the local code

What I have is `octohatrack.py` which goes
```
import octohatrack
octohatrack.main()
```
 
But this doesn't run on systems without `octohatrack` the package already installed.

```
pkg_resources.DistributionNotFound: The 'octohatrack' distribution was not found and is required by the application
```

What I think might be happening is that I've done doofed the `__init__.py` file, so that I can't import the local file functionality. The current setup works gives a valid `setup.py` and installation mechanism, but it just doesn't work for local invocation. 

However, if you install octohatrack locally, the code in the local package doesn't actually run (provable by changing the current directory files to change the functionality, and have those changes be seen in the output. 

I think this is something to do with modules, packages, setup.py's, and the hackery I did in #1

**Comment by glasnt** [comment]
I don't think is a problem any more. I think. Note to self: next Python sprint, get a guru to take a look at this.

**Comment by glasnt** [comment]
So, TLDR of a conversation with the incredible @mjtamlyn: 

given a sufficiently setup virtualenvwrapper, using `pip install -e .` should allow for invoking of the local copy of whatever in-progress code is going on, given I'm in the virtual environment. 

Virtualenvwrapper and python 3 are things that require more hacking locally, however.  Once I get it working, it'll be documented so others can do the things :clap:

**Comment by mjtamlyn** [comment]
Instructions which should work for setting up py3.4 built in venvs http://tutorial.djangogirls.org/en/django_installation/#virtual-environment

**Comment by glasnt** [comment]
belated thanks, @mjtamlyn

I think I totally have this working locally now. Pending adding this hint to the README in "Local Development"

**Comment by glasnt** [comment]
Going to keep this going over in #66
