### ISSUE TITLE
Updating README.md with a couple of n00b Q & As

### ISSUE THREAD

**Issue by KirstieJane** [LABHR/octohatrack#75]
Firstly - thank you for making this! My team and I really want to recognise all types of contributions to our project and this seems like a great way to do just that!

I've just installed `octohatrack` on a windows machine (successfully) and it took me a little while to figure out a couple of the options so I though I'd offer to update the `README.md` with the info I was looking for to make it easier for the next person.

Specifically, the `README.md` doesn't explain the `-g, --generate-html` option which meant I was scratching my head for a little bit trying to figure out what I was supposed to do with the `.json` file that was generated. It wasn't hard to figure out, but I just thought I could add a little note to point out how useful it is!

Then there was one other question: am I right that a simple use case would be to download this locally and then every now and again re-run the code to update your html file? Is there a better/different way that you'd recommend?

Thanks again!

**Comment by glasnt** [comment]
Hi @KirstieJane! Thank you for taking the time to describe the issues you're having. 

Yay a windows installation! I hadn't tested it on a Windows box before, but I'm glad it all worked. 

I have been lax and I haven't updated the documentation, and for that I apologise. Once I release the new 0.4 version, I'll be updating the documentation to show that you don't need any flags to run the report.

On the point of `--generate-html` - we have https://labhr.github.io/js-hatrack/ which is a web-based version of the HTML reporting, which includes such wonderful features as being faster and prettier than the Python-generated HTML. Once it's got the same features as the Python version, I'll be removing the HTML generation from the published version of the package. 

If you want to try out the https://labhr.github.io/js-hatrack/ app and see how it works for you as something you can reload when required, as opposed to having to download and re-run periodically.

**Comment by KirstieJane** [comment]
Ah! How fun is that link?! I love it! Even better :)

Happy to do any user testing on Windows if necessary going forwards but I think you've already made the tool I'm looking for!

**Comment by KirstieJane** [comment]
Oh - hang on - is it possible to have a link from https://labhr.github.io/js-hatrack/ that doesn't require one to be logged into GitHub?

**Comment by glasnt** [comment]
Unfortunately not - unless you're authenticated, you don't get enough API
tokens to complete the report.

If you run the command line app without authentication, you get an explicit
warning about this.

I hope this isn't a blocker for you.

Unrelated - Can I ask which repo you're running these reports on?

**Comment by KirstieJane** [comment]
Gotcha. We'll figure out a combo of the static html from the command line tool and the fabulous interactive link. And on that note, does this work for you? https://labhr.github.io/js-hatrack/#repo=kirstiejane/Stemmrolemodels

The repo is https://github.com/KirstieJane/STEMMRoleModels

We're very early on but a major goal is to build a really positive community. And this way of saying thank you is excellent :)

**Comment by glasnt** [comment]
Yup, the link does work :) 


I'll update the doco once I get a bit of time to clean up things and publish 0.4.

If you see any other issues, especially running on Windows, don't hesitate to let me know

And thank you again for reaching out. It's been invaluable 👏

**Comment by KirstieJane** [comment]
Thank you! I love this tool.

I hacked something together just in case anyone wanted to do the following. If it's useful please feel free to use it/share etc (maybe it should be on the js-hatrack repo page?). And if I'm doing something bad then please also tell me to cease and desist!

**How to save a static version of the js-hatrack page**

* **Problem**: At the moment you can only see the contributors for a github repo via https://labhr.github.io/js-hatrack/ if you're logged into GitHub (because the information is pulled in real time to create the webpage and you need to be verified by GitHub to be allowed to send enough requests to compile the information). I'd like to host a page on my website that means ***anyone*** can see who has contributed without requiring the buy in of creating a GitHub account.

* **Solution**: A project member logs in with GitHub and create the lovely looking page via https://labhr.github.io/js-hatrack/ then saves a non-dynamic copy using the [Scrapbook](https://addons.mozilla.org/en-US/firefox/addon/scrapbook/) Firefox add on.

**Instructions**

* Install the [Scrapbook](https://addons.mozilla.org/en-US/firefox/addon/scrapbook/) Firefox add on
* Create the Lets Build a Hat Rack contributers page for your project:
  * Go to https://labhr.github.io/js-hatrack/
  * Login with GitHub 
  * Enter the repository name
  * Click go!
* Save the page to your local machine using Scrapbook (click `alt` to see the Firefox browser menu). * Copy this folder (which is helpfully named with the date and time that you downloaded it) to your website's folder.

**And you're done!** :tada: :sparkles: 

Thank you to [this answer](http://superuser.com/questions/405669/save-static-version-of-a-webpage-to-be-available-offline) on StackExchange for providing this hack solution!

**Comment by glasnt** [comment]
I've added this as a PR to hatrack, thank you so much! :tada:

**Comment by KirstieJane** [comment]
Fantastic. And thank you for the awesome tool!
