### ISSUE TITLE
Timeouts / running out of tokens

### ISSUE THREAD

**Issue by tleeuwenburg** [LABHR/octohatrack#91]
Hi there,

I'm trying to run this on fchollet/keras. It's an active project. I am using a github token to increase the number of requests, but it keeps running out of tokens anyway. I'm not sure if the results from previous runs are cached (re-runs will help) or not (re-runs don't help).

I could use some advice on how to run this on a bigger project.

Thanks,
-Tennessee

**Comment by glasnt** [comment]
Hi @tleeuwenburg 

Yes, with the implicit caching, subsequent runs should see it already has the results for specific API calls. The repo you mentioned is .. quite large, and unfortunately I have no alternative for you other than just calling the script once an hour until it 'runs clean'.

**Comment by rixx** [comment]
I think it would be nice to print intermediary results: cleaning duplicates from everything that has been cached and that has been found in this run, with a large warning that the list is incomplete.

**Comment by glasnt** [comment]
The cache is now clean-as. Hopefully this resolves everything in this issue. ✨
