### ISSUE TITLE
Reduce caching

### ISSUE THREAD

**Issue by rixx** [LABHR/octohatrack#94]
I just let octohatrack run on a moderately large repository and the cache file easily reached 1MB after two runs, which is a bit large for inspection (especially since dumping everything in one line makes syntax highlighting take a while …). I think reducing the amount of data written to the cache file might be a good idea :)

**Comment by glasnt** [comment]
Hi @rixx, sorry for the slow reply. That's a really good idea. I know so much more Python than I did when I originally wrote this, so a refactor (including fixing the caching system) sounds like a good idea ✨

**Comment by rixx** [comment]
Just to clarify: are you planning on doing this (at some point, I mean)? I could try my hand at it, too, but only if you don't want to.

**Comment by glasnt** [comment]
@rixx I'm planning on doing this, as a refactor
